"""BayesIQ Dashboard — Generated by BayesIQ Data Audit Kit."""

import json
import os
import re

import pandas as pd
import plotly.express as px
import streamlit as st

st.set_page_config(page_title="BayesIQ Dashboard", layout="wide")

@st.cache_data
def load_data(path):
    """Load and clean the dataset from a file path."""
    if path.endswith('.parquet'):
        df = pd.read_parquet(path)
    else:
        df = pd.read_csv(path)

    if "transaction_date" in df.columns:
        df["transaction_date"] = pd.to_datetime(df["transaction_date"], utc=True)

    # Remove near-duplicate rows
    dedup_cols = ["account_id", "merchant_id", "transaction_type", "payment_method", "merchant_category", "risk_tier", "geography", "amount", "fee_amount", "settlement_amount", "settlement_days", "transaction_date", "settlement_date", "fraud_flag", "settled_flag", "transaction_flag", "chargeback_flag"]
    before = len(df)
    df = df.drop_duplicates(subset=dedup_cols, keep='first')
    after = len(df)
    df.attrs["rows_deduped"] = before - after

    return df


@st.cache_data
def load_uploaded(file):
    """Load and clean a dataset from an uploaded file."""
    if file.name.endswith('.parquet'):
        df = pd.read_parquet(file)
    else:
        df = pd.read_csv(file)

    if "transaction_date" in df.columns:
        df["transaction_date"] = pd.to_datetime(df["transaction_date"], utc=True)

    # Remove near-duplicate rows
    dedup_cols = ["account_id", "merchant_id", "transaction_type", "payment_method", "merchant_category", "risk_tier", "geography", "amount", "fee_amount", "settlement_amount", "settlement_days", "transaction_date", "settlement_date", "fraud_flag", "settled_flag", "transaction_flag", "chargeback_flag"]
    before = len(df)
    df = df.drop_duplicates(subset=dedup_cols, keep='first')
    after = len(df)
    df.attrs["rows_deduped"] = before - after

    return df


def main():
    st.title("BayesIQ Data Dashboard")

    st.sidebar.header("Data Source")
    uploaded_file = st.sidebar.file_uploader(
        "Upload CSV or Parquet",
        type=["csv", "parquet", "pq"],
        help="Drag and drop a file here, or click to browse."
    )
    default_path = "data/raw_month_3.csv"
    data_path = st.sidebar.text_input("Or enter file path", value=default_path)

    # Load from upload or path
    df = None
    if uploaded_file is not None:
        try:
            df = load_uploaded(uploaded_file)
        except Exception as e:
            st.error(f"Could not load uploaded file: {e}")
            return
    elif data_path:
        try:
            df = load_data(data_path)
        except Exception as e:
            st.error(f"Could not load dataset: {e}")
            return
    else:
        st.info("Upload a file or enter a dataset path in the sidebar to get started.")
        return

    # Auto-detect period: weekly for short datasets, monthly otherwise
    _period = "M"
    if "transaction_date" in df.columns:
        _ts_range = df["transaction_date"].max() - df["transaction_date"].min()
        if _ts_range.days <= 45:
            _period = "W"

    # --- Sidebar Filters ---
    st.sidebar.header("Filters")

    if "transaction_date" in df.columns:
        min_date = df["transaction_date"].min().date()
        max_date = df["transaction_date"].max().date()
        date_range = st.sidebar.date_input(
            "Date Range",
            value=(min_date, max_date),
            min_value=min_date,
            max_value=max_date,
        )
        if len(date_range) == 2:
            df = df[(df["transaction_date"].dt.date >= date_range[0]) &
                    (df["transaction_date"].dt.date <= date_range[1])]

    if "transaction_type" in df.columns:
        transaction_type_opts = sorted(df["transaction_type"].dropna().unique().tolist())
        transaction_type_sel = st.sidebar.multiselect(
            "transaction_type",
            options=transaction_type_opts,
            default=transaction_type_opts,
        )
        df = df[df["transaction_type"].isin(transaction_type_sel)]

    if "payment_method" in df.columns:
        payment_method_opts = sorted(df["payment_method"].dropna().unique().tolist())
        payment_method_sel = st.sidebar.multiselect(
            "payment_method",
            options=payment_method_opts,
            default=payment_method_opts,
        )
        df = df[df["payment_method"].isin(payment_method_sel)]

    if "merchant_category" in df.columns:
        merchant_category_opts = sorted(df["merchant_category"].dropna().unique().tolist())
        merchant_category_sel = st.sidebar.multiselect(
            "merchant_category",
            options=merchant_category_opts,
            default=merchant_category_opts,
        )
        df = df[df["merchant_category"].isin(merchant_category_sel)]

    if "risk_tier" in df.columns:
        risk_tier_opts = sorted(df["risk_tier"].dropna().unique().tolist())
        risk_tier_sel = st.sidebar.multiselect(
            "risk_tier",
            options=risk_tier_opts,
            default=risk_tier_opts,
        )
        df = df[df["risk_tier"].isin(risk_tier_sel)]

    if "geography" in df.columns:
        geography_opts = sorted(df["geography"].dropna().unique().tolist())
        geography_sel = st.sidebar.multiselect(
            "geography",
            options=geography_opts,
            default=geography_opts,
        )
        df = df[df["geography"].isin(geography_sel)]

    if "settlement_days" in df.columns:
        settlement_days_opts = sorted(df["settlement_days"].dropna().unique().tolist())
        settlement_days_sel = st.sidebar.multiselect(
            "settlement_days",
            options=settlement_days_opts,
            default=settlement_days_opts,
        )
        df = df[df["settlement_days"].isin(settlement_days_sel)]

    if "fraud_flag" in df.columns:
        fraud_flag_opts = sorted(df["fraud_flag"].dropna().unique().tolist())
        fraud_flag_sel = st.sidebar.multiselect(
            "fraud_flag",
            options=fraud_flag_opts,
            default=fraud_flag_opts,
        )
        df = df[df["fraud_flag"].isin(fraud_flag_sel)]

    if "settled_flag" in df.columns:
        settled_flag_opts = sorted(df["settled_flag"].dropna().unique().tolist())
        settled_flag_sel = st.sidebar.multiselect(
            "settled_flag",
            options=settled_flag_opts,
            default=settled_flag_opts,
        )
        df = df[df["settled_flag"].isin(settled_flag_sel)]

    if "chargeback_flag" in df.columns:
        chargeback_flag_opts = sorted(df["chargeback_flag"].dropna().unique().tolist())
        chargeback_flag_sel = st.sidebar.multiselect(
            "chargeback_flag",
            options=chargeback_flag_opts,
            default=chargeback_flag_opts,
        )
        df = df[df["chargeback_flag"].isin(chargeback_flag_sel)]

    st.sidebar.metric("Rows (filtered)", f"{len(df):,}")
    deduped = df.attrs.get("rows_deduped", 0)
    if deduped:
        st.sidebar.metric("Rows deduped", f"{deduped:,}")

    tabs = st.tabs(["Metrics", "Data Quality", "Raw Data"])

    with tabs[0]:
        st.header("Business Metrics")

        st.subheader("Transaction Volume")

        _dim_options_transaction_volume = ['transaction_type', 'payment_method', 'merchant_category', 'risk_tier', 'geography', 'settlement_days', 'fraud_flag', 'settled_flag', 'chargeback_flag']
        _sel_dim_transaction_volume = st.selectbox(
            "Break down by", ["(none)"] + _dim_options_transaction_volume,
            key="dim_picker_transaction_volume")

        metric_df = df
        grouped = metric_df.groupby(metric_df["transaction_date"].dt.to_period(_period)).size().reset_index()
        grouped.columns = ["period", "transaction_volume"]
        grouped["period"] = grouped["period"].astype(str)

        fig = px.bar(grouped, x="period", y="transaction_volume", title="Transaction Volume Over Time")
        st.plotly_chart(fig, use_container_width=True)

        if _sel_dim_transaction_volume != "(none)":
            _dim_col = _sel_dim_transaction_volume
            _dim_label = _dim_col.replace("_", " ").title()
            if _dim_col in metric_df.columns:
                dim_grouped = metric_df.groupby([metric_df["transaction_date"].dt.to_period(_period), _dim_col]).size().reset_index()
                dim_grouped.columns = ["period", _dim_col, "transaction_volume"]
                dim_grouped["period"] = dim_grouped["period"].astype(str)
                fig2 = px.bar(dim_grouped, x="period", y="transaction_volume", color=_dim_col, title=f"Transaction Volume by {_dim_label}", barmode="group")
                st.plotly_chart(fig2, use_container_width=True)

        st.divider()

        st.subheader("Fee Revenue")

        _dim_options_fee_revenue = ['transaction_type', 'payment_method', 'merchant_category', 'risk_tier', 'geography', 'settlement_days', 'fraud_flag', 'settled_flag', 'chargeback_flag']
        _sel_dim_fee_revenue = st.selectbox(
            "Break down by", ["(none)"] + _dim_options_fee_revenue,
            key="dim_picker_fee_revenue")

        metric_df = df
        if "fee_amount" not in metric_df.columns:
            st.warning("Column \"fee_amount\" not found in data — skipping Fee Revenue.")
        else:
            grouped = metric_df.groupby(metric_df["transaction_date"].dt.to_period(_period))["fee_amount"].sum().reset_index()
            grouped.columns = ["period", "fee_revenue"]
            grouped["period"] = grouped["period"].astype(str)

            fig = px.bar(grouped, x="period", y="fee_revenue", title="Fee Revenue Over Time")
            st.plotly_chart(fig, use_container_width=True)

            # Dimension breakdown
        if _sel_dim_fee_revenue != "(none)":
            _dim_col = _sel_dim_fee_revenue
            _dim_label = _dim_col.replace("_", " ").title()
            if _dim_col in metric_df.columns and "fee_amount" in metric_df.columns:
                dim_grouped = metric_df.groupby([metric_df["transaction_date"].dt.to_period(_period), _dim_col])["fee_amount"].sum().reset_index()
                dim_grouped.columns = ["period", _dim_col, "fee_revenue"]
                dim_grouped["period"] = dim_grouped["period"].astype(str)
                fig2 = px.bar(dim_grouped, x="period", y="fee_revenue", color=_dim_col, title=f"Fee Revenue by {_dim_label}", barmode="group")
                st.plotly_chart(fig2, use_container_width=True)


        st.divider()

        st.subheader("Settlement Time")

        _dim_options_settlement_time = ['transaction_type', 'payment_method', 'merchant_category', 'risk_tier', 'geography', 'settlement_days', 'fraud_flag', 'settled_flag', 'chargeback_flag']
        _sel_dim_settlement_time = st.selectbox(
            "Break down by", ["(none)"] + _dim_options_settlement_time,
            key="dim_picker_settlement_time")

        metric_df = df
        if "settlement_days" not in metric_df.columns:
            st.warning("Column \"settlement_days\" not found in data — skipping Settlement Time.")
        else:
            grouped = metric_df.groupby(metric_df["transaction_date"].dt.to_period(_period))["settlement_days"].mean().reset_index()
            grouped.columns = ["period", "settlement_time"]
            grouped["period"] = grouped["period"].astype(str)

            fig = px.line(grouped, x="period", y="settlement_time", title="Settlement Time Over Time", markers=True)
            st.plotly_chart(fig, use_container_width=True)

            # Dimension breakdown
        if _sel_dim_settlement_time != "(none)":
            _dim_col = _sel_dim_settlement_time
            _dim_label = _dim_col.replace("_", " ").title()
            if _dim_col in metric_df.columns and "settlement_days" in metric_df.columns:
                dim_grouped = metric_df.groupby([metric_df["transaction_date"].dt.to_period(_period), _dim_col])["settlement_days"].mean().reset_index()
                dim_grouped.columns = ["period", _dim_col, "settlement_time"]
                dim_grouped["period"] = dim_grouped["period"].astype(str)
                fig2 = px.line(dim_grouped, x="period", y="settlement_time", color=_dim_col, title=f"Settlement Time by {_dim_label}", markers=True)
                st.plotly_chart(fig2, use_container_width=True)


        st.divider()

        st.subheader("Fraud Exposure")

        _dim_options_fraud_exposure = ['transaction_type', 'payment_method', 'merchant_category', 'risk_tier', 'geography', 'settlement_days', 'fraud_flag', 'settled_flag', 'chargeback_flag']
        _sel_dim_fraud_exposure = st.selectbox(
            "Break down by", ["(none)"] + _dim_options_fraud_exposure,
            key="dim_picker_fraud_exposure")

        num_df = df[(df["fraud_flag"] == 1)]
        den_df = df[(df["settled_flag"] == 1)]
        den_grouped = den_df.groupby(den_df["transaction_date"].dt.to_period(_period)).size()
        num_grouped = num_df.groupby(num_df["transaction_date"].dt.to_period(_period)).size().reindex(den_grouped.index, fill_value=0)
        ratio_df = (num_grouped / den_grouped).fillna(0).reset_index()
        ratio_df.columns = ["period", "fraud_exposure"]
        ratio_df["period"] = ratio_df["period"].astype(str)

        if ratio_df.empty:
            st.info("No data for Fraud Exposure in this period.")
        else:
            fig = px.line(ratio_df, x="period", y="fraud_exposure", title="Fraud Exposure Over Time", markers=True)
            st.plotly_chart(fig, use_container_width=True)

        if _sel_dim_fraud_exposure != "(none)":
            _dim_col = _sel_dim_fraud_exposure
            _dim_label = _dim_col.replace("_", " ").title()
            if _dim_col in num_df.columns:
                num_dim = num_df.groupby([num_df["transaction_date"].dt.to_period(_period), _dim_col]).size().unstack(fill_value=0)
                den_dim = den_df.groupby([den_df["transaction_date"].dt.to_period(_period), _dim_col]).size().unstack(fill_value=0)
                ratio_dim = (num_dim / den_dim).stack().reset_index()
                ratio_dim.columns = ["period", _dim_col, "fraud_exposure"]
                ratio_dim["period"] = ratio_dim["period"].astype(str)
                fig2 = px.line(ratio_dim, x="period", y="fraud_exposure", color=_dim_col, title=f"Fraud Exposure by {_dim_label}", markers=True)
                st.plotly_chart(fig2, use_container_width=True)

        st.divider()

        st.subheader("Payment Method Growth")

        _dim_options_payment_method_growth = ['transaction_type', 'payment_method', 'merchant_category', 'risk_tier', 'geography', 'settlement_days', 'fraud_flag', 'settled_flag', 'chargeback_flag']
        _sel_dim_payment_method_growth = st.selectbox(
            "Break down by", ["(none)"] + _dim_options_payment_method_growth,
            key="dim_picker_payment_method_growth")

        metric_df = df
        grouped = metric_df.groupby(metric_df["transaction_date"].dt.to_period(_period)).size().reset_index()
        grouped.columns = ["period", "payment_method_growth"]
        grouped["period"] = grouped["period"].astype(str)

        fig = px.bar(grouped, x="period", y="payment_method_growth", title="Payment Method Growth Over Time")
        st.plotly_chart(fig, use_container_width=True)

        if _sel_dim_payment_method_growth != "(none)":
            _dim_col = _sel_dim_payment_method_growth
            _dim_label = _dim_col.replace("_", " ").title()
            if _dim_col in metric_df.columns:
                dim_grouped = metric_df.groupby([metric_df["transaction_date"].dt.to_period(_period), _dim_col]).size().reset_index()
                dim_grouped.columns = ["period", _dim_col, "payment_method_growth"]
                dim_grouped["period"] = dim_grouped["period"].astype(str)
                fig2 = px.bar(dim_grouped, x="period", y="payment_method_growth", color=_dim_col, title=f"Payment Method Growth by {_dim_label}", barmode="group")
                st.plotly_chart(fig2, use_container_width=True)

        st.divider()

    with tabs[1]:
        st.header("Data Quality Summary")
        st.metric("Total Issues Found", 3)

        col1, col2, col3, col4 = st.columns(4)
        col1.metric("Critical", 0)
        col2.metric("High", 2)
        col3.metric("Medium", 1)
        col4.metric("Low", 0)

        st.info("This dashboard applies automatic cleaning: value canonicalization and near-duplicate deduplication. The issues below were detected in the raw data before cleaning.")

        st.subheader("Findings")
        st.markdown("**1. [HIGH]** Near-duplicate rows detected (54 rows)")
        st.markdown("**2. [HIGH]** Null values in required column: merchant_id (28 rows)")
        st.markdown("**3. [MEDIUM]** fee_revenue misreported for 2025-12 (off by +8.4%) (1 rows)")

    with tabs[2]:
        st.header("Raw Data")
        st.dataframe(df.head(1000), use_container_width=True)


if __name__ == "__main__":
    main()
